# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFinal():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_final(self):
    self.driver.get("https://play1.automationcamp.ir/login.html")
    self.driver.set_window_size(938, 705)
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.ID, "user").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("admin")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "rad_small").click()
    self.driver.find_element(By.ID, "select_flavor").click()
    dropdown = self.driver.find_element(By.ID, "select_flavor")
    dropdown.find_element(By.XPATH, "//option[. = 'Pepperoni']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(3) .form-check:nth-child(1) > .form-check-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(3) .form-check:nth-child(1) > .form-check-label").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(3) .form-check:nth-child(1) > .form-check-label")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) .form-check-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) .form-check-label").click()
    self.driver.find_element(By.ID, "quantity").send_keys("1")
    self.driver.find_element(By.ID, "quantity").click()
    self.driver.find_element(By.ID, "quantity").send_keys("2")
    self.driver.find_element(By.ID, "quantity").click()
    element = self.driver.find_element(By.ID, "quantity")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "quantity").send_keys("1")
    self.driver.find_element(By.ID, "quantity").click()
    self.driver.find_element(By.ID, "submit_button").click()
  
